name: CI Pipeline

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    scan:
        name: SonarQube Scan # does works? or what?
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: SonarQube Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
              projectBaseDir: ./products-microservice # Path to the root of the project

    scan-root:
        name: SonarQube Scan Root
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0