name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan-products-microservice:
    name: SonarQube Scan for Products Microservice
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.1

    # - name: SonarQube Scan
    #   uses: sonarsource/sonarcloud-github-action@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   with:
    #     projectBaseDir: ./products-microservice

  scan-users-microservice:
    name: SonarQube Scan for Users Microservice
    runs-on: ubuntu-latest
    env:
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.8

    - name: Grant execute permission for gradlew
      run: chmod +x ./user-microservice/gradlew    

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./user-microservice

    # - name: SonarQube Scan
    #   uses: sonarsource/sonarcloud-github-action@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   with:
    #     projectBaseDir: ./user-microservice
    #     args: "-Dsonar.java.binaries=./build/classes/java/main"
